# Generated by Django 3.2.6 on 2021-08-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일')),
                ('age_range', models.CharField(blank=True, choices=[('10~19', '10대'), ('20~29', '20대'), ('30~39', '30대'), ('40~49', '40대'), ('50~59', '50대'), ('60~69', '60대'), ('70~79', '70대'), ('80~89', '80대')], max_length=16, null=True, verbose_name='연령대')),
                ('nickname', models.CharField(blank=True, max_length=64, null=True, verbose_name='닉네임')),
                ('gender', models.CharField(blank=True, choices=[('male', '남'), ('female', '여')], max_length=8, null=True, verbose_name='성별')),
                ('profile_public', models.BooleanField(default=True, verbose_name='프로필 공개 허용 여부')),
                ('number_of_pet', models.IntegerField(default=0, verbose_name='등록 반려동물 수')),
                ('warning_stack', models.IntegerField(default=0, verbose_name='신고 누적 횟수')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원',
                'db_table': 'user',
            },
        ),
    ]
