# Generated by Django 3.2.6 on 2021-08-04 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social',
            field=models.ForeignKey(blank=True, default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='user.socialplatform'),
        ),
    ]
