# Generated by Django 3.2.6 on 2021-08-10 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=64, verbose_name='이름')),
                ('gender', models.CharField(blank=True, choices=[('male', '수컷'), ('female', '암컷')], max_length=8, null=True, verbose_name='성별')),
                ('pet_image', models.ImageField(null=True, upload_to='', verbose_name='프로필 사진')),
                ('introducing_pet', models.TextField(null=True, verbose_name='반려동물 소개')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='주인 정보')),
            ],
            options={
                'verbose_name': '반려동물 정보',
                'verbose_name_plural': '반려동물 정보',
                'db_table': 'user_Pet',
            },
        ),
    ]
